### PR TITLE
Palette and themes updates

### PR DESCRIPTION
**Pull request by KottV**
Hi,

What includes:

Fix tab's border color
Add borderCheckbox for checkbox border
Add foregroundInactive for inactive tab's label
New ArcDark and BB themes. Updated bundles themes.

### CODE REVIEW

**Comment by ryukau** [comment]
Thanks for the patch!

Just one more thing, please add your name to the license at the top of changed files. Also add your name and contact info (email address) to `License/README.md`. If you are not ok to put contact info, skip it.

**Comment by KottV** [comment]
Oh, this is so negligible part of code :)
I'll put info into files headers.
But not sure where to put it in License/README.md

**Comment by ryukau** [comment]
Put it above or below of my name (Takamitsu Endo) by your preference. I'll sort the name as alphabet order when the list is getting long (10 or more).

Format I saw other project using was something like this:

```
(c) 2020 Takamitsu Endo <ryukau@gmail.com>
```

I'll add my email address after the merge.

**Comment by ryukau** [comment]
Merged. Thanks again!

**Pull request merged**
